version: '3.8'

services:
  # 游릱 Backend (Spring Boot)
  moro_backend:
    build: ./Moro-App
    container_name: moro_backend
    networks:
      - moro-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/moro_db
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 游릴 Frontend (React + Vite)
  frontend:
    build: ./MoroScan
    container_name: moro_frontend
    ports:
      - "80:80"  # Cambiado a puerto 80 est치ndar para producci칩n
    networks:
      - moro-network
    depends_on:
      moro_backend:
        condition: service_healthy
    environment:
      - VITE_API_BASE_URL=http://moro_backend:8080

  # 游릳 PostgreSQL
  postgres_db:
    image: postgres:16.2-alpine
    container_name: db-postgres-moro
    networks:
      - moro-network
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: moro_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d moro_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 游린 pgAdmin (opcional para producci칩n)
  pgadmin_service:
    image: dpage/pgadmin4:8.7
    container_name: pgadmin4_moro
    networks:
      - moro-network
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres_db

networks:
  moro-network:
    driver: bridge

volumes:
  postgres_data: